### ISSUE TITLE
Current Findings to fix

### ISSUE THREAD

**Issue by mikesz88** [Kenzie-Tech-Solutions/theRoyalCanine#2]
- [x] Title needs to be capitalized: The Royal Canine
- [x] When a modal appears for photos, please have the ability for the black part to be clicked on/to exit, just like the exit icon. 
- [x] Finish GitHub pages deployment

    I have updated you as admin to this repo. Let me know if that does not work for deploying to GitHub pages. 
    
    Don't forget to:
    1. Delete your `intial-setup` branch
    2. pull your changes on the dev branch
    3. Create a new branch for these changes
    4. Then work normally
This is typical for work.

**Comment by Iconians** [comment]
ok got those changes made
