### ISSUE TITLE
Responsive Tweaks

### ISSUE THREAD

**Issue by mikesz88** [Kenzie-Tech-Solutions/theRoyalCanine#5]
- [x] Home Screen
  - The Title and image are in a row format and must be stacked.
    - ![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/7f815656-ca4e-450e-8656-c533c4b927e6)
    - ![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/5769e095-3617-4d7f-9b5c-9aa299a1d19b)
  - The Heading section is illegible. When completing the other ticket, the legibility should be fixed here with that, but it is still not setup for mobile. The size of the 'paragraph' should be max 300px. The title heading seems to be centered, but Business Hours and Location does not (that could do with 'business hours' being longer so maybe do a space-around so it focuses on the edges. Unsure, but play with it. Worse case scenario could be be having them stacked when it is on mobile view). 
  - On the contact info section: 
    - Capitalized contact info
- [x] Business Details & FAQ
  - ![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/23de2a5c-28d2-4f14-8e45-c592f6e68fc1)
  - There is a gap between header and 'business details'. Please make that much smaller in this mobile screen.
  - Please capitalize all headers
  - The business details section seems off-centered.
    - ![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/c0f99a25-7a63-44cd-9332-6620c250335a)
  - Based on the example website: https://www.shampoochgahanna.com/about it seems we are missing some styles. Can you please make sure you imitate the style. I know there is no disclaimers and we are adding a FAQ at the bottom, but the font seems different, horizional lines are missing, and I am unsure how you are going to add business hours location and phone information. Use fake data so we can see what it looks like. 
  - The FAQ questions in mobile form is okay until we click on the questions. That width is too small. 
    - ![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/644ad1cc-c90b-4642-a3b5-65841121e485)
    - It might be best to change them to modals when clicked to avoid this issue || The width should take a wider space on the mobile screen and not the width of the question itself.
    - Again the navbar here is not mobile friendly. 
- [x] Photo Gallery
  - The navbar (check all pages for this)
  - The modal is not mobile friendly
    - ![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/8fdfa37c-b0a9-4d02-b3b4-4c24f6e1d7f1)
- [x] Events
  - Navbar only
  - Will see what client says about this.

**Comment by Iconians** [comment]
went through all four tasks and completed them, the gallery modal was a little harder to figure out due to the picture you provided not happening on the dev server but I think I figured it out to a width that needs to be unset in mobile view and the navbar was I think was part of it as well
